import { BookContent } from "../bookContent";

const U = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=70`;

export const NETWORKING_2026_CONTENT: BookContent = {
  cover: {
    tagline: "Connecting the World: From Bits to Software-Defined Clouds.",
    blurb: "The definitive 2026 guide to networking. Whether you're just starting with IP addresses or designing global SD-WAN architectures, this book covers the protocols, hardware, and software that power the modern internet."
  },
  toc: [
    "Introduction: The Nervous System of Civilization",
    "Chapter 1: Networking Basics: The OSI Model & TCP/IP",
    "Chapter 2: Routing and Switching in the Modern Age",
    "Chapter 3: Wireless Technologies: Wi-Fi 7 and Beyond",
    "Chapter 4: The 5G & 6G Revolution: Mobile Edge Computing",
    "Chapter 5: Network Security: VPNs, Firewalls, and SASE",
    "Chapter 6: Software-Defined Networking (SDN) & SD-WAN",
    "Chapter 7: Cloud Networking: AWS, Azure, and Multi-Cloud",
    "Chapter 8: Data Center Architecture & Leaf-Spine Fabrics",
    "Chapter 9: The Future: Quantum Networking & Satellite Links",
    "Appendix: Networking Lab Setup & Troubleshooting"
  ],
  chapters: [
    {
      title: "Introduction: The Nervous System of Civilization",
      pages: [
        "Networking is the invisible infrastructure that connects every aspect of modern life. From the moment you wake up and check your smartphone to the global transactions that power the economy, everything relies on the movement of data across a vast and complex web of cables, satellites, and radio waves.\n\nIn 2026, networking is no longer just about connecting computers; it's about connecting billions of autonomous devices, AI agents, and cloud workloads in a seamless, low-latency ecosystem. This book is designed to take you from the fundamental building blocks to the cutting edge of network architecture.",
        "Whether you are a student, a software developer, or a seasoned network engineer, understanding how data moves is critical. We will demystify the acronyms and protocols, providing a clear and practical roadmap for mastering the nervous system of our digital civilization.",
        "The shift towards software-defined everything has transformed the role of the network professional. We will explore how automation and virtualization are changing the way we build and manage networks at scale."
      ],
      images: [U("photo-1451187580459-43490279c0fa")]
    },
    {
      title: "Chapter 1: Networking Basics: The OSI Model & TCP/IP",
      pages: [
        "Every network journey begins with the OSI (Open Systems Interconnection) model. We break down the seven layers, from the physical cables and signals to the application layer where users interact with the web. Understanding these boundaries is essential for troubleshooting and design.\n\nWe then dive into the TCP/IP suite, the practical implementation of these concepts that powers the internet. We look at IP addressing (IPv4 and the long-awaited dominance of IPv6), submasking, and the critical roles of TCP and UDP in ensuring reliable or fast delivery.",
        "The importance of DNS (Domain Name System) and DHCP (Dynamic Host Configuration Protocol) cannot be overstated. We explain how these foundational services allow us to use human-readable names and automatically connect devices to a network.",
        "Basic packet analysis using tools like Wireshark is a core skill. We show how to capture and inspect traffic to understand what's really happening on the wire."
      ],
      images: [U("photo-1558494949-ef010cbdcc31")]
    },
    {
      title: "Chapter 2: Routing and Switching in the Modern Age",
      pages: [
        "Switches and routers are the traffic cops of the network. We look at how Layer 2 switches use MAC addresses to move data within a local area network (LAN), and how Layer 3 routers use IP addresses to move data between different networks.\n\nWe explore modern routing protocols like BGP (Border Gateway Protocol), OSPF, and EIGRP, and how they allow the internet to dynamically adapt to failures and find the most efficient paths for data. The concept of 'Virtual LANs' (VLANs) for network segmentation is also covered in depth.",
        "In 2026, switching has moved towards high-speed 400GbE and 800GbE interfaces. We examine the hardware innovations that allow modern data centers to handle the massive traffic generated by AI training and video streaming.",
        "We also look at 'Layer 3 Switching', where the boundaries between routing and switching blur, providing wire-speed routing performance within the data center."
      ],
      images: [U("photo-1563089145-599997674d42")]
    },
    {
      title: "Chapter 3: Wireless Technologies: Wi-Fi 7 and Beyond",
      pages: [
        "Wireless is the primary way most of us connect to the network. We explore the latest Wi-Fi 7 (802.11be) standards, which offer multi-gigabit speeds and significantly lower latency by using wider channels and multi-link operation (MLO).\n\nWe discuss the challenges of RF (Radio Frequency) design, including interference, signal attenuation, and the use of MIMO (Multiple Input Multiple Output) to increase capacity and reliability in dense environments.",
        "Security in wireless networks is paramount. We analyze WPA3 and the transition away from legacy, vulnerable protocols like WEP and WPA2. We also look at the role of 'Wireless LAN Controllers' (WLCs) in managing large-scale campus networks.",
        "Beyond Wi-Fi, we examine emerging technologies like Li-Fi (Light Fidelity), which uses light waves for high-speed, secure indoor communication."
      ],
      images: [U("photo-1523961131990-5ea7c61b2107")]
    },
    {
      title: "Chapter 4: The 5G & 6G Revolution: Mobile Edge Computing",
      pages: [
        "Mobile networks have evolved far beyond just making phone calls. 5G and the early research into 6G are designed to support a massive number of IoT devices and high-bandwidth applications like augmented reality (AR) and autonomous vehicles.\n\nWe look at 'Network Slicing', which allows a single physical 5G network to be divided into multiple virtual networks with different performance characteristics, and 'Multi-access Edge Computing' (MEC), which brings compute resources closer to the user to reduce latency.",
        "The shift towards 'Open RAN' (Radio Access Network) is breaking down proprietary hardware silos, allowing for more innovation and competition in the mobile infrastructure market.",
        "6G is expected to operate in the terahertz frequency range, enabling speeds in the hundreds of gigabits per second and supporting 'Integrated Sensing and Communication' (ISAC), where the network can detect and track physical objects."
      ],
      images: [U("photo-1562408590-e32931084e23")]
    },
    {
      title: "Chapter 5: Network Security: VPNs, Firewalls, and SASE",
      pages: [
        "A network without security is a liability. We explore the implementation of Next-Generation Firewalls (NGFWs) that provide deep packet inspection, intrusion prevention (IPS), and application-level control.\n\nWe look at the different types of Virtual Private Networks (VPNs), including Site-to-Site and Remote Access, and how protocols like IPsec and WireGuard provide secure encrypted tunnels over the public internet.",
        "The transition to SASE (Secure Access Service Edge) is a major trend in 2026. SASE combines networking (SD-WAN) and security (FWaaS, CASB, ZTNA) into a single cloud-delivered service, providing consistent security for users wherever they are.",
        "DDoS (Distributed Denial of Service) protection is also covered, explaining how global scrubbing centers can identify and mitigate massive traffic attacks before they reach the target network."
      ],
      images: [U("photo-1563206767-5b18f218e8de")]
    },
    {
      title: "Chapter 6: Software-Defined Networking (SDN) & SD-WAN",
      pages: [
        "Software-Defined Networking (SDN) decouples the control plane from the data plane, allowing for centralized management and automation of the network. We look at the role of SDN controllers and how they use APIs to program the behavior of the entire network fabric.\n\nSD-WAN (Software-Defined Wide Area Network) applies these principles to the enterprise WAN, allowing organizations to intelligently route traffic over a mix of MPLS, broadband, and 5G links based on application performance and cost.",
        "Automation is the key to scaling modern networks. We explore the use of Python, Ansible, and Terraform for 'Infrastructure as Code' (IaC), allowing engineers to deploy and update network configurations in minutes rather than days.",
        "Intent-Based Networking (IBN) is the next evolution, where the administrator defines the *intent* (e.g., 'ensure video traffic has high priority'), and the network automatically configures itself to achieve that goal."
      ],
      images: [U("photo-1551434678-e076c223a692")]
    },
    {
      title: "Chapter 7: Cloud Networking: AWS, Azure, and Multi-Cloud",
      pages: [
        "Cloud networking requires a shift in mindset from physical cables to virtual constructs. We explore VPCs (Virtual Private Clouds), subnets, routing tables, and internet gateways in the major cloud providers.\n\nWe look at the different ways to connect on-premises data centers to the cloud, including VPNs and dedicated private links like AWS Direct Connect and Azure ExpressRoute. Multi-cloud networking, where workloads span multiple providers, is also discussed in detail.",
        "Cloud-native load balancers and Content Delivery Networks (CDNs) are essential for scaling and ensuring a fast global user experience. We explain how these services work and how to configure them for optimal performance.",
        "Security in the cloud is a shared responsibility. We analyze the use of 'Security Groups' and 'Network ACLs' to provide fine-grained control over traffic entering and leaving your cloud resources."
      ],
      images: [U("photo-1460925895917-afdab827c52f")]
    },
    {
      title: "Chapter 8: Data Center Architecture & Leaf-Spine Fabrics",
      pages: [
        "Modern data centers have moved away from traditional three-tier architectures towards 'Leaf-Spine' fabrics. This design provides consistent, low-latency, and high-bandwidth connectivity for east-west traffic between servers.\n\nWe look at the role of VXLAN (Virtual Extensible LAN) in creating virtual Layer 2 networks over a Layer 3 underlay, allowing for seamless VM migration and network stretching across the data center.",
        "Network visibility and telemetry are critical for managing large-scale data center fabrics. We explore the use of streaming telemetry and AI-driven analytics to identify bottlenecks and predict failures before they impact the business.",
        "Energy efficiency is also a major concern. We examine how modern data center designs, including liquid cooling and intelligent power management, are reducing the environmental impact of our digital infrastructure."
      ],
      images: [U("photo-1558494949-ef010cbdcc31")]
    },
    {
      title: "Chapter 9: The Future: Quantum Networking & Satellite Links",
      pages: [
        "The future of networking is reaching into space and the quantum realm. We look at the rise of LEO (Low Earth Orbit) satellite constellations like Starlink, which are providing high-speed, low-latency internet to the most remote parts of the planet.\n\nQuantum networking is emerging as the ultimate way to achieve secure communication. We explore the concepts of 'Quantum Key Distribution' (QKD) and 'Quantum Entanglement', which allow for the transmission of data that is fundamentally impossible to eavesdrop on.",
        "The 'Internet of Everything' (IoE) will connect not just devices, but people, processes, and data in a globally integrated ecosystem. We discuss the challenges and opportunities of this hyper-connected future.",
        "As the network becomes more complex and autonomous, the role of the network professional will continue to evolve. Success will depend on the ability to combine deep technical knowledge with a strategic understanding of the business and a commitment to ethics and security."
      ],
      images: [U("photo-1451187580459-43490279c0fa")]
    },
    {
      title: "Appendix: Networking Lab Setup & Troubleshooting",
      pages: [
        "Learning networking requires hands-on practice. We provide a guide to setting up your own home lab using virtualized environments like GNS3, Cisco Packet Tracer, and Eve-NG.\n\nWe also share a collection of essential troubleshooting commands and techniques for Windows, Linux, and Cisco IOS, helping you solve common connectivity problems quickly and efficiently.",
        "Remember: the best way to learn is by doing. Don't be afraid to break things in your lab, as that's where the real learning happens. Good luck on your journey to becoming a networking master!"
      ],
      images: [U("photo-1518770660439-4636190af475")]
    }
  ]
};
