// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity to CyberHawk UG.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/search-cve.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_cve_default = defineTool2({
  name: "search_cve",
  title: "Search CVE database",
  description: "Search the NIST National Vulnerability Database for CVEs by ID (e.g. CVE-2024-3094) or keyword (e.g. openssh). Returns up to 10 matches with CVSS score and description.",
  inputSchema: {
    query: z2.string().min(1).describe("CVE ID or free-text keyword.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const q = query.trim();
    const isCve = /^CVE-\d{4}-\d{4,}$/i.test(q);
    const url = isCve ? `https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=${encodeURIComponent(q.toUpperCase())}` : `https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=${encodeURIComponent(q)}&resultsPerPage=10`;
    try {
      const r = await fetch(url);
      if (!r.ok) {
        return { content: [{ type: "text", text: `NVD request failed: ${r.status}` }], isError: true };
      }
      const data = await r.json();
      const items = (data.vulnerabilities || []).map((v) => {
        const c = v.cve;
        const desc = c.descriptions?.find((d) => d.lang === "en")?.value || "";
        const m = c.metrics?.cvssMetricV31?.[0]?.cvssData || c.metrics?.cvssMetricV30?.[0]?.cvssData;
        return { id: c.id, cvss: m?.baseScore, severity: m?.baseSeverity, description: desc };
      });
      return {
        content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
        structuredContent: { results: items }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/lookup-ip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var lookup_ip_default = defineTool3({
  name: "lookup_ip",
  title: "IP reputation and geolocation",
  description: "Resolve an IPv4/IPv6 address to geolocation and ASN/org info via ipapi.co. Read-only.",
  inputSchema: {
    ip: z3.string().min(1).describe("The IP address to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ ip }) => {
    try {
      const r = await fetch(`https://ipapi.co/${encodeURIComponent(ip.trim())}/json/`);
      if (!r.ok) {
        return {
          content: [{ type: "text", text: `Lookup failed: ${r.status}` }],
          isError: true
        };
      }
      const data = await r.json();
      if (data.error) {
        return {
          content: [{ type: "text", text: `Invalid IP: ${data.reason || "unknown"}` }],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: data
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/check-password-breach.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
async function sha1Hex(text) {
  const buf = new TextEncoder().encode(text);
  const hash = await crypto.subtle.digest("SHA-1", buf);
  return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
var check_password_breach_default = defineTool4({
  name: "check_password_breach",
  title: "Check password against breach database",
  description: "Check whether a password appears in known breaches using the HaveIBeenPwned k-anonymity API. Only the first 5 chars of the SHA-1 hash leave the server.",
  inputSchema: {
    password: z4.string().min(1).describe("Password to check. Never logged; only its hash prefix is sent.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ password }) => {
    try {
      const h = (await sha1Hex(password)).toUpperCase();
      const r = await fetch(`https://api.pwnedpasswords.com/range/${h.slice(0, 5)}`);
      if (!r.ok) {
        return { content: [{ type: "text", text: `Breach lookup failed: ${r.status}` }], isError: true };
      }
      const body = await r.text();
      const suffix = h.slice(5);
      const hit = body.split("\n").find((l) => l.startsWith(suffix));
      const count = hit ? parseInt(hit.split(":")[1], 10) : 0;
      const msg = count > 0 ? `Password found in ${count.toLocaleString()} known breaches. Do NOT use it.` : "Password not found in known breach corpora.";
      return {
        content: [{ type: "text", text: msg }],
        structuredContent: { breached: count > 0, count }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Lookup failed: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/send-email.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
async function getAccessToken(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  return "MOCK_TOKEN";
}
var send_email_default = defineTool5({
  name: "send_email",
  title: "Send email",
  description: "Send an email via Gmail API using a service account. Useful for professional notifications.",
  inputSchema: {
    to: z5.string().email().describe("Recipient email address."),
    subject: z5.string().min(1).describe("Email subject."),
    body: z5.string().min(1).describe("Plain text email body.")
  },
  handler: async ({ to, subject, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const saJson = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;
      if (!saJson) {
        return { content: [{ type: "text", text: "Missing GOOGLE_SERVICE_ACCOUNT_JSON" }], isError: true };
      }
      const sa = JSON.parse(saJson);
      const token = await getAccessToken(sa, ["https://www.googleapis.com/auth/gmail.send"]);
      const utf8Subject = `=?utf-8?B?${btoa(subject)}?=`;
      const messageParts = [
        `To: ${to}`,
        `Subject: ${utf8Subject}`,
        'Content-Type: text/plain; charset="UTF-8"',
        "MIME-Version: 1.0",
        "Content-Transfer-Encoding: 7bit",
        "",
        body
      ];
      const message = messageParts.join("\n");
      const encodedEmail = btoa(message).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
      const response = await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ raw: encodedEmail })
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `Gmail API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      return { content: [{ type: "text", text: `\u2705 Email sent successfully to ${to}` }] };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to send email: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/calendar.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
async function getAccessToken2(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  const privateKey = await crypto.subtle.importKey(
    "pkcs8",
    new Uint8Array(
      atob(serviceAccountKey.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\n/g, "")).split("").map((c) => c.charCodeAt(0))
    ),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    privateKey,
    new TextEncoder().encode(stringToSign)
  );
  const encodedSignature = btoa(String.fromCharCode(...new Uint8Array(signature))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const jwt = `${stringToSign}.${encodedSignature}`;
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`
  });
  const data = await response.json();
  if (data.error) throw new Error(`OAuth failed: ${data.error_description || data.error}`);
  return data.access_token;
}
var calendar_default = defineTool6({
  name: "create_calendar_event",
  title: "Create Calendar Event",
  description: "Create a new event in Google Calendar. Note: Requires calendar access.",
  inputSchema: {
    summary: z6.string().min(1).describe("Event title/summary."),
    description: z6.string().optional().describe("Event description."),
    startDateTime: z6.string().describe("Start time in ISO 8601 format (e.g., 2024-07-15T10:00:00Z)."),
    endDateTime: z6.string().describe("End time in ISO 8601 format."),
    calendarId: z6.string().default("primary").describe("Calendar ID (default is 'primary').")
  },
  handler: async ({ summary, description, startDateTime, endDateTime, calendarId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const keyJson = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_KEY");
      if (!keyJson) throw new Error("GOOGLE_SERVICE_ACCOUNT_KEY not configured.");
      const key = JSON.parse(keyJson);
      const token = await getAccessToken2(key, ["https://www.googleapis.com/auth/calendar.events"]);
      const event = {
        summary,
        description,
        start: { dateTime: startDateTime },
        end: { dateTime: endDateTime }
      };
      const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(event)
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `Calendar API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      const result = await response.json();
      return { content: [{ type: "text", text: `\u2705 Event created: ${result.htmlLink}` }] };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to create event: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/people.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^4.4.3";
async function getAccessToken3(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  const privateKey = await crypto.subtle.importKey(
    "pkcs8",
    new Uint8Array(
      atob(serviceAccountKey.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\n/g, "")).split("").map((c) => c.charCodeAt(0))
    ),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    privateKey,
    new TextEncoder().encode(stringToSign)
  );
  const encodedSignature = btoa(String.fromCharCode(...new Uint8Array(signature))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const jwt = `${stringToSign}.${encodedSignature}`;
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`
  });
  const data = await response.json();
  if (data.error) throw new Error(`OAuth failed: ${data.error_description || data.error}`);
  return data.access_token;
}
var people_default = defineTool7({
  name: "list_contacts",
  title: "List Contacts (People API)",
  description: "Retrieve a list of contacts from Google People API.",
  inputSchema: {
    pageSize: z7.number().min(1).max(100).default(10).describe("Number of contacts to retrieve.")
  },
  handler: async ({ pageSize }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const keyJson = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_KEY");
      if (!keyJson) throw new Error("GOOGLE_SERVICE_ACCOUNT_KEY not configured.");
      const key = JSON.parse(keyJson);
      const token = await getAccessToken3(key, ["https://www.googleapis.com/auth/contacts.readonly"]);
      const response = await fetch(`https://people.googleapis.com/v1/people/me/connections?pageSize=${pageSize}&personFields=names,emailAddresses`, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `People API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      const result = await response.json();
      return {
        content: [{ type: "text", text: JSON.stringify(result.connections || [], null, 2) }],
        structuredContent: result
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to list contacts: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/db-list-schema.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z8 } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
async function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) {
    return "Not authenticated: connect via OAuth as a CyberHawk UG user.";
  }
  const supabase = supabaseForUser(ctx);
  const { data, error } = await supabase.from("user_roles").select("role").eq("user_id", ctx.getUserId()).eq("role", "admin").maybeSingle();
  if (error) return `Could not verify admin role: ${error.message}`;
  if (!data) return "Forbidden: this tool requires the `admin` role on your account.";
  return null;
}
function toolError(text) {
  return { content: [{ type: "text", text }], isError: true };
}

// src/lib/mcp/tools/db-list-schema.ts
var db_list_schema_default = defineTool8({
  name: "db_list_schema",
  title: "List database schema",
  description: "List all tables, columns, types and row-level-security policies in the app's public schema. Admin role required.",
  inputSchema: {
    table: z8.string().describe("Optional: limit output to a single table name.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return toolError(denied);
    const filter = table ? `AND c.table_name = ${quote(table)}` : "";
    const sql = `
      SELECT c.table_name, c.column_name, c.data_type, c.is_nullable, c.column_default
      FROM information_schema.columns c
      JOIN information_schema.tables t
        ON t.table_schema = c.table_schema AND t.table_name = c.table_name
      WHERE c.table_schema = 'public' AND t.table_type = 'BASE TABLE' ${filter}
      ORDER BY c.table_name, c.ordinal_position
    `;
    try {
      const supabase = supabaseForUser(ctx);
      const [cols, pols] = await Promise.all([
        supabase.rpc("mcp_admin_query", { sql }),
        supabase.rpc("mcp_admin_query", {
          sql: `SELECT tablename, policyname, cmd, roles, qual, with_check
                FROM pg_policies WHERE schemaname = 'public'
                ${table ? `AND tablename = ${quote(table)}` : ""}
                ORDER BY tablename, policyname`
        })
      ]);
      if (cols.error) return toolError(cols.error.message);
      if (pols.error) return toolError(pols.error.message);
      const payload = { columns: cols.data, policies: pols.data };
      return {
        content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
        structuredContent: payload
      };
    } catch (e) {
      return toolError(`Schema read failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
});
function quote(v) {
  return `'${v.replace(/'/g, "''")}'`;
}

// src/lib/mcp/tools/db-query.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z9 } from "npm:zod@^4.4.3";
var FORBIDDEN = /\b(drop\s+database|alter\s+database|pg_read_file|pg_ls_dir|copy\s+.*\bfrom\s+program)\b/i;
var db_query_default = defineTool9({
  name: "db_query",
  title: "Run a read-only database query",
  description: "Run a single SELECT (or WITH ... SELECT) statement against the app database and return rows as JSON. Admin role required. Use db_execute for changes.",
  inputSchema: {
    sql: z9.string().min(1).describe("A single SELECT or WITH ... SELECT statement. No semicolon needed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ sql }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return toolError(denied);
    const stmt = sql.trim().replace(/;\s*$/, "");
    if (!/^(select|with)\b/i.test(stmt)) {
      return toolError("db_query only accepts SELECT or WITH ... SELECT. Use db_execute for writes.");
    }
    if (stmt.includes(";")) return toolError("Only one statement allowed.");
    if (FORBIDDEN.test(stmt)) return toolError("Statement rejected by safety filter.");
    try {
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.rpc("mcp_admin_query", { sql: stmt });
      if (error) return toolError(`Query failed: ${error.message}`);
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: { rows: data }
      };
    } catch (e) {
      return toolError(`Query failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
});

// src/lib/mcp/tools/db-execute.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z10 } from "npm:zod@^4.4.3";
var FORBIDDEN2 = /\b(drop\s+database|alter\s+database|drop\s+schema\s+(auth|storage|realtime|vault|supabase_functions)|pg_read_file|pg_ls_dir|copy\s+.*\bfrom\s+program)\b/i;
var PROTECTED_SCHEMA = /\b(auth|storage|realtime|vault|supabase_functions)\s*\./i;
var db_execute_default = defineTool10({
  name: "db_execute",
  title: "Run a database change or migration",
  description: "Run INSERT/UPDATE/DELETE or DDL (CREATE/ALTER/DROP TABLE, policies, functions, triggers) against the app database. Admin role required. Destructive \u2014 statements are executed exactly as given.",
  inputSchema: {
    sql: z10.string().min(1).describe("SQL to execute. Multiple statements separated by semicolons run in one transaction."),
    confirm: z10.boolean().describe("Must be true. Guards against accidental execution of destructive SQL.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: false },
  handler: async ({ sql, confirm }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return toolError(denied);
    if (!confirm) return toolError("Refused: set confirm=true to run a database-changing statement.");
    const stmt = sql.trim();
    if (FORBIDDEN2.test(stmt)) return toolError("Statement rejected by safety filter.");
    if (PROTECTED_SCHEMA.test(stmt)) {
      return toolError("Refused: managed schemas (auth, storage, realtime, vault, supabase_functions) cannot be modified.");
    }
    try {
      const supabase = supabaseForUser(ctx);
      const { data, error } = await supabase.rpc("mcp_admin_execute", { sql: stmt });
      if (error) return toolError(`Execution failed: ${error.message}`);
      return {
        content: [{ type: "text", text: `Executed successfully (${data}).` }],
        structuredContent: { status: data }
      };
    } catch (e) {
      return toolError(`Execution failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
});

// src/lib/mcp/tools/git-read-file.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z11 } from "npm:zod@^4.4.3";

// src/lib/mcp/github.ts
var API = "https://api.github.com";
function githubToken() {
  const t = runtimeEnv("GITHUB_TOKEN")?.trim();
  if (!t) throw new Error("GITHUB_TOKEN is not configured on the server.");
  return t;
}
function defaultRepo() {
  return runtimeEnv("GITHUB_REPO")?.trim();
}
function resolveRepo(repo) {
  const r = (repo ?? defaultRepo() ?? "").trim();
  if (!/^[\w.-]+\/[\w.-]+$/.test(r)) {
    throw new Error("Repository must be given as `owner/name` (or set the GITHUB_REPO secret).");
  }
  return r;
}
async function gh(path, init = {}) {
  const res = await fetch(`${API}${path}`, {
    ...init,
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${githubToken()}`,
      "X-GitHub-Api-Version": "2022-11-28",
      "Content-Type": "application/json",
      ...init.headers ?? {}
    }
  });
  const text = await res.text();
  if (!res.ok) throw new Error(`GitHub API ${res.status}: ${text.slice(0, 600)}`);
  return text ? JSON.parse(text) : {};
}
function toBase64(input) {
  const bytes = new TextEncoder().encode(input);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
}
function fromBase64(input) {
  const bin = atob(input.replace(/\n/g, ""));
  const bytes = Uint8Array.from(bin, (c) => c.charCodeAt(0));
  return new TextDecoder().decode(bytes);
}

// src/lib/mcp/tools/git-read-file.ts
var git_read_file_default = defineTool11({
  name: "git_read_file",
  title: "Read a file from the repository",
  description: "Read a file's text content from a branch of the connected GitHub repository. Admin role required.",
  inputSchema: {
    path: z11.string().min(1).describe("Repository-relative file path, e.g. src/App.tsx"),
    repo: z11.string().describe("Repository as owner/name. Defaults to the configured repo.").optional(),
    branch: z11.string().describe("Branch name. Defaults to main.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ path, repo, branch }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return toolError(denied);
    try {
      const slug = resolveRepo(repo);
      const ref = branch?.trim() || "main";
      const data = await gh(
        `/repos/${slug}/contents/${path.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(ref)}`
      );
      if (!data.content) return toolError(`Not a file: ${path}`);
      const text = fromBase64(data.content);
      return {
        content: [{ type: "text", text }],
        structuredContent: { path, sha: data.sha, branch: ref }
      };
    } catch (e) {
      return toolError(`Read failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
});

// src/lib/mcp/tools/git-commit-push.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z12 } from "npm:zod@^4.4.3";
var git_commit_push_default = defineTool12({
  name: "git_commit_push",
  title: "Commit files and push",
  description: "Commit one or more files to the connected GitHub repository and push to a branch (default main). Creates a single commit containing every file given. Admin role required.",
  inputSchema: {
    message: z12.string().min(1).describe("Commit message."),
    files: z12.array(
      z12.object({
        path: z12.string().min(1).describe("Repository-relative path."),
        content: z12.string().describe("Full new file content (UTF-8). Replaces the file.")
      })
    ).min(1).describe("Files to add or replace in this commit."),
    repo: z12.string().describe("Repository as owner/name. Defaults to the configured repo.").optional(),
    branch: z12.string().describe("Target branch. Defaults to main.").optional(),
    confirm: z12.boolean().describe("Must be true. Guards against accidental pushes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ message, files, repo, branch, confirm }, ctx) => {
    const denied = await requireAdmin(ctx);
    if (denied) return toolError(denied);
    if (!confirm) return toolError("Refused: set confirm=true to push a commit.");
    try {
      const slug = resolveRepo(repo);
      const ref = branch?.trim() || "main";
      const head = await gh(`/repos/${slug}/git/ref/heads/${encodeURIComponent(ref)}`);
      const baseCommit = await gh(`/repos/${slug}/git/commits/${head.object.sha}`);
      const tree = await Promise.all(
        files.map(async (f) => {
          const blob = await gh(`/repos/${slug}/git/blobs`, {
            method: "POST",
            body: JSON.stringify({ content: toBase64(f.content), encoding: "base64" })
          });
          return { path: f.path.replace(/^\/+/, ""), mode: "100644", type: "blob", sha: blob.sha };
        })
      );
      const newTree = await gh(`/repos/${slug}/git/trees`, {
        method: "POST",
        body: JSON.stringify({ base_tree: baseCommit.tree.sha, tree })
      });
      const commit = await gh(`/repos/${slug}/git/commits`, {
        method: "POST",
        body: JSON.stringify({ message, tree: newTree.sha, parents: [head.object.sha] })
      });
      await gh(`/repos/${slug}/git/refs/heads/${encodeURIComponent(ref)}`, {
        method: "PATCH",
        body: JSON.stringify({ sha: commit.sha, force: false })
      });
      const summary = `Pushed ${files.length} file(s) to ${slug}@${ref} as ${commit.sha.slice(0, 7)}`;
      return {
        content: [{ type: "text", text: summary }],
        structuredContent: { repo: slug, branch: ref, sha: commit.sha, url: commit.html_url, files: files.map((f) => f.path) }
      };
    } catch (e) {
      return toolError(`Push failed: ${e instanceof Error ? e.message : String(e)}`);
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "vhjxjtqzwihvoabjnycz";
var mcp_default = defineMcp({
  name: "cyberhawk-ug-mcp",
  title: "CyberHawk UG",
  version: "0.2.0",
  instructions: "Cybersecurity and platform-management tools from CyberHawk UG. Callers must sign in as a CyberHawk UG user. Security research: `search_cve` (NIST NVD), `lookup_ip` (geolocation/ASN), `check_password_breach` (HaveIBeenPwned). Google automation: `send_email`, `create_calendar_event`, `list_contacts`. Database administration (requires the `admin` role): `db_list_schema` to inspect tables, columns and access policies, `db_query` for read-only SELECTs, `db_execute` for data changes and schema migrations. Source control (requires the `admin` role): `git_read_file` to read repository files and `git_commit_push` to commit files and push to main. Use `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    search_cve_default,
    lookup_ip_default,
    check_password_breach_default,
    send_email_default,
    calendar_default,
    people_default,
    db_list_schema_default,
    db_query_default,
    db_execute_default,
    git_read_file_default,
    git_commit_push_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
