// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity to CyberHawk UG.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/search-cve.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_cve_default = defineTool2({
  name: "search_cve",
  title: "Search CVE database",
  description: "Search the NIST National Vulnerability Database for CVEs by ID (e.g. CVE-2024-3094) or keyword (e.g. openssh). Returns up to 10 matches with CVSS score and description.",
  inputSchema: {
    query: z2.string().min(1).describe("CVE ID or free-text keyword.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const q = query.trim();
    const isCve = /^CVE-\d{4}-\d{4,}$/i.test(q);
    const url = isCve ? `https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=${encodeURIComponent(q.toUpperCase())}` : `https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=${encodeURIComponent(q)}&resultsPerPage=10`;
    try {
      const r = await fetch(url);
      if (!r.ok) {
        return { content: [{ type: "text", text: `NVD request failed: ${r.status}` }], isError: true };
      }
      const data = await r.json();
      const items = (data.vulnerabilities || []).map((v) => {
        const c = v.cve;
        const desc = c.descriptions?.find((d) => d.lang === "en")?.value || "";
        const m = c.metrics?.cvssMetricV31?.[0]?.cvssData || c.metrics?.cvssMetricV30?.[0]?.cvssData;
        return { id: c.id, cvss: m?.baseScore, severity: m?.baseSeverity, description: desc };
      });
      return {
        content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
        structuredContent: { results: items }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/lookup-ip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var lookup_ip_default = defineTool3({
  name: "lookup_ip",
  title: "IP reputation and geolocation",
  description: "Resolve an IPv4/IPv6 address to geolocation and ASN/org info via ipapi.co. Read-only.",
  inputSchema: {
    ip: z3.string().min(1).describe("The IP address to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ ip }) => {
    try {
      const r = await fetch(`https://ipapi.co/${encodeURIComponent(ip.trim())}/json/`);
      if (!r.ok) {
        return {
          content: [{ type: "text", text: `Lookup failed: ${r.status}` }],
          isError: true
        };
      }
      const data = await r.json();
      if (data.error) {
        return {
          content: [{ type: "text", text: `Invalid IP: ${data.reason || "unknown"}` }],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: data
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/check-password-breach.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
async function sha1Hex(text) {
  const buf = new TextEncoder().encode(text);
  const hash = await crypto.subtle.digest("SHA-1", buf);
  return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
var check_password_breach_default = defineTool4({
  name: "check_password_breach",
  title: "Check password against breach database",
  description: "Check whether a password appears in known breaches using the HaveIBeenPwned k-anonymity API. Only the first 5 chars of the SHA-1 hash leave the server.",
  inputSchema: {
    password: z4.string().min(1).describe("Password to check. Never logged; only its hash prefix is sent.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ password }) => {
    try {
      const h = (await sha1Hex(password)).toUpperCase();
      const r = await fetch(`https://api.pwnedpasswords.com/range/${h.slice(0, 5)}`);
      if (!r.ok) {
        return { content: [{ type: "text", text: `Breach lookup failed: ${r.status}` }], isError: true };
      }
      const body = await r.text();
      const suffix = h.slice(5);
      const hit = body.split("\n").find((l) => l.startsWith(suffix));
      const count = hit ? parseInt(hit.split(":")[1], 10) : 0;
      const msg = count > 0 ? `Password found in ${count.toLocaleString()} known breaches. Do NOT use it.` : "Password not found in known breach corpora.";
      return {
        content: [{ type: "text", text: msg }],
        structuredContent: { breached: count > 0, count }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Lookup failed: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "cyberhawk-ug-mcp",
  title: "CyberHawk UG",
  version: "0.1.0",
  instructions: "Cybersecurity tools from CyberHawk UG. Use `search_cve` to look up vulnerabilities in the NIST NVD, `lookup_ip` for IP geolocation and ASN info, `check_password_breach` for HaveIBeenPwned password checks, and `echo` to verify connectivity.",
  tools: [echo_default, search_cve_default, lookup_ip_default, check_password_breach_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
