// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back. Useful for verifying MCP connectivity to CyberHawk UG.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/search-cve.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var search_cve_default = defineTool2({
  name: "search_cve",
  title: "Search CVE database",
  description: "Search the NIST National Vulnerability Database for CVEs by ID (e.g. CVE-2024-3094) or keyword (e.g. openssh). Returns up to 10 matches with CVSS score and description.",
  inputSchema: {
    query: z2.string().min(1).describe("CVE ID or free-text keyword.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query }) => {
    const q = query.trim();
    const isCve = /^CVE-\d{4}-\d{4,}$/i.test(q);
    const url = isCve ? `https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=${encodeURIComponent(q.toUpperCase())}` : `https://services.nvd.nist.gov/rest/json/cves/2.0?keywordSearch=${encodeURIComponent(q)}&resultsPerPage=10`;
    try {
      const r = await fetch(url);
      if (!r.ok) {
        return { content: [{ type: "text", text: `NVD request failed: ${r.status}` }], isError: true };
      }
      const data = await r.json();
      const items = (data.vulnerabilities || []).map((v) => {
        const c = v.cve;
        const desc = c.descriptions?.find((d) => d.lang === "en")?.value || "";
        const m = c.metrics?.cvssMetricV31?.[0]?.cvssData || c.metrics?.cvssMetricV30?.[0]?.cvssData;
        return { id: c.id, cvss: m?.baseScore, severity: m?.baseSeverity, description: desc };
      });
      return {
        content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
        structuredContent: { results: items }
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/lookup-ip.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.4.3";
var lookup_ip_default = defineTool3({
  name: "lookup_ip",
  title: "IP reputation and geolocation",
  description: "Resolve an IPv4/IPv6 address to geolocation and ASN/org info via ipapi.co. Read-only.",
  inputSchema: {
    ip: z3.string().min(1).describe("The IP address to look up.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ ip }) => {
    try {
      const r = await fetch(`https://ipapi.co/${encodeURIComponent(ip.trim())}/json/`);
      if (!r.ok) {
        return {
          content: [{ type: "text", text: `Lookup failed: ${r.status}` }],
          isError: true
        };
      }
      const data = await r.json();
      if (data.error) {
        return {
          content: [{ type: "text", text: `Invalid IP: ${data.reason || "unknown"}` }],
          isError: true
        };
      }
      return {
        content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
        structuredContent: data
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Lookup failed: ${e.message}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/check-password-breach.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^4.4.3";
async function sha1Hex(text) {
  const buf = new TextEncoder().encode(text);
  const hash = await crypto.subtle.digest("SHA-1", buf);
  return Array.from(new Uint8Array(hash)).map((b) => b.toString(16).padStart(2, "0")).join("");
}
var check_password_breach_default = defineTool4({
  name: "check_password_breach",
  title: "Check password against breach database",
  description: "Check whether a password appears in known breaches using the HaveIBeenPwned k-anonymity API. Only the first 5 chars of the SHA-1 hash leave the server.",
  inputSchema: {
    password: z4.string().min(1).describe("Password to check. Never logged; only its hash prefix is sent.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ password }) => {
    try {
      const h = (await sha1Hex(password)).toUpperCase();
      const r = await fetch(`https://api.pwnedpasswords.com/range/${h.slice(0, 5)}`);
      if (!r.ok) {
        return { content: [{ type: "text", text: `Breach lookup failed: ${r.status}` }], isError: true };
      }
      const body = await r.text();
      const suffix = h.slice(5);
      const hit = body.split("\n").find((l) => l.startsWith(suffix));
      const count = hit ? parseInt(hit.split(":")[1], 10) : 0;
      const msg = count > 0 ? `Password found in ${count.toLocaleString()} known breaches. Do NOT use it.` : "Password not found in known breach corpora.";
      return {
        content: [{ type: "text", text: msg }],
        structuredContent: { breached: count > 0, count }
      };
    } catch (e) {
      return { content: [{ type: "text", text: `Lookup failed: ${e.message}` }], isError: true };
    }
  }
});

// src/lib/mcp/tools/send-email.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^4.4.3";
async function getAccessToken(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  return "MOCK_TOKEN";
}
var send_email_default = defineTool5({
  name: "send_email",
  title: "Send email",
  description: "Send an email via Gmail API using a service account. Useful for professional notifications.",
  inputSchema: {
    to: z5.string().email().describe("Recipient email address."),
    subject: z5.string().min(1).describe("Email subject."),
    body: z5.string().min(1).describe("Plain text email body.")
  },
  handler: async ({ to, subject, body }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const saJson = process.env.GOOGLE_SERVICE_ACCOUNT_JSON;
      if (!saJson) {
        return { content: [{ type: "text", text: "Missing GOOGLE_SERVICE_ACCOUNT_JSON" }], isError: true };
      }
      const sa = JSON.parse(saJson);
      const token = await getAccessToken(sa, ["https://www.googleapis.com/auth/gmail.send"]);
      const utf8Subject = `=?utf-8?B?${btoa(subject)}?=`;
      const messageParts = [
        `To: ${to}`,
        `Subject: ${utf8Subject}`,
        'Content-Type: text/plain; charset="UTF-8"',
        "MIME-Version: 1.0",
        "Content-Transfer-Encoding: 7bit",
        "",
        body
      ];
      const message = messageParts.join("\n");
      const encodedEmail = btoa(message).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
      const response = await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages/send", {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify({ raw: encodedEmail })
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `Gmail API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      return { content: [{ type: "text", text: `\u2705 Email sent successfully to ${to}` }] };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to send email: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/calendar.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^4.4.3";
async function getAccessToken2(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  const privateKey = await crypto.subtle.importKey(
    "pkcs8",
    new Uint8Array(
      atob(serviceAccountKey.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\n/g, "")).split("").map((c) => c.charCodeAt(0))
    ),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    privateKey,
    new TextEncoder().encode(stringToSign)
  );
  const encodedSignature = btoa(String.fromCharCode(...new Uint8Array(signature))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const jwt = `${stringToSign}.${encodedSignature}`;
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`
  });
  const data = await response.json();
  if (data.error) throw new Error(`OAuth failed: ${data.error_description || data.error}`);
  return data.access_token;
}
var calendar_default = defineTool6({
  name: "create_calendar_event",
  title: "Create Calendar Event",
  description: "Create a new event in Google Calendar. Note: Requires calendar access.",
  inputSchema: {
    summary: z6.string().min(1).describe("Event title/summary."),
    description: z6.string().optional().describe("Event description."),
    startDateTime: z6.string().describe("Start time in ISO 8601 format (e.g., 2024-07-15T10:00:00Z)."),
    endDateTime: z6.string().describe("End time in ISO 8601 format."),
    calendarId: z6.string().default("primary").describe("Calendar ID (default is 'primary').")
  },
  handler: async ({ summary, description, startDateTime, endDateTime, calendarId }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const keyJson = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_KEY");
      if (!keyJson) throw new Error("GOOGLE_SERVICE_ACCOUNT_KEY not configured.");
      const key = JSON.parse(keyJson);
      const token = await getAccessToken2(key, ["https://www.googleapis.com/auth/calendar.events"]);
      const event = {
        summary,
        description,
        start: { dateTime: startDateTime },
        end: { dateTime: endDateTime }
      };
      const response = await fetch(`https://www.googleapis.com/calendar/v3/calendars/${encodeURIComponent(calendarId)}/events`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        },
        body: JSON.stringify(event)
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `Calendar API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      const result = await response.json();
      return { content: [{ type: "text", text: `\u2705 Event created: ${result.htmlLink}` }] };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to create event: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/tools/people.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^4.4.3";
async function getAccessToken3(serviceAccountKey, scopes) {
  const header = { alg: "RS256", typ: "JWT" };
  const now = Math.floor(Date.now() / 1e3);
  const claim = {
    iss: serviceAccountKey.client_email,
    scope: scopes.join(" "),
    aud: "https://oauth2.googleapis.com/token",
    exp: now + 3600,
    iat: now
  };
  const encodedHeader = btoa(JSON.stringify(header));
  const encodedClaim = btoa(JSON.stringify(claim));
  const stringToSign = `${encodedHeader}.${encodedClaim}`;
  const privateKey = await crypto.subtle.importKey(
    "pkcs8",
    new Uint8Array(
      atob(serviceAccountKey.private_key.replace(/-----(BEGIN|END) PRIVATE KEY-----|\n/g, "")).split("").map((c) => c.charCodeAt(0))
    ),
    { name: "RSASSA-PKCS1-v1_5", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "RSASSA-PKCS1-v1_5",
    privateKey,
    new TextEncoder().encode(stringToSign)
  );
  const encodedSignature = btoa(String.fromCharCode(...new Uint8Array(signature))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
  const jwt = `${stringToSign}.${encodedSignature}`;
  const response = await fetch("https://oauth2.googleapis.com/token", {
    method: "POST",
    headers: { "Content-Type": "application/x-www-form-urlencoded" },
    body: `grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer&assertion=${jwt}`
  });
  const data = await response.json();
  if (data.error) throw new Error(`OAuth failed: ${data.error_description || data.error}`);
  return data.access_token;
}
var people_default = defineTool7({
  name: "list_contacts",
  title: "List Contacts (People API)",
  description: "Retrieve a list of contacts from Google People API.",
  inputSchema: {
    pageSize: z7.number().min(1).max(100).default(10).describe("Number of contacts to retrieve.")
  },
  handler: async ({ pageSize }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated: sign in via OAuth to use this tool." }], isError: true };
    }
    try {
      const keyJson = Deno.env.get("GOOGLE_SERVICE_ACCOUNT_KEY");
      if (!keyJson) throw new Error("GOOGLE_SERVICE_ACCOUNT_KEY not configured.");
      const key = JSON.parse(keyJson);
      const token = await getAccessToken3(key, ["https://www.googleapis.com/auth/contacts.readonly"]);
      const response = await fetch(`https://people.googleapis.com/v1/people/me/connections?pageSize=${pageSize}&personFields=names,emailAddresses`, {
        method: "GET",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        const err = await response.json();
        return { content: [{ type: "text", text: `People API Error: ${JSON.stringify(err)}` }], isError: true };
      }
      const result = await response.json();
      return {
        content: [{ type: "text", text: JSON.stringify(result.connections || [], null, 2) }],
        structuredContent: result
      };
    } catch (e) {
      return {
        content: [{ type: "text", text: `Failed to list contacts: ${e instanceof Error ? e.message : String(e)}` }],
        isError: true
      };
    }
  }
});

// src/lib/mcp/index.ts
var projectRef = "vhjxjtqzwihvoabjnycz";
var mcp_default = defineMcp({
  name: "cyberhawk-ug-mcp",
  title: "CyberHawk UG",
  version: "0.1.0",
  instructions: "Cybersecurity tools from CyberHawk UG. Callers must sign in as a CyberHawk UG user. Use `search_cve` to look up vulnerabilities in the NIST NVD, `lookup_ip` for IP geolocation and ASN info, `check_password_breach` for HaveIBeenPwned password checks, `send_email` for Gmail automation, `create_calendar_event` for scheduling, `list_contacts` for contact management, and `echo` to verify connectivity.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    echo_default,
    search_cve_default,
    lookup_ip_default,
    check_password_breach_default,
    send_email_default,
    calendar_default,
    people_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
