import type { VercelRequest, VercelResponse } from "@vercel/node";

interface NewsAPIArticle {
  title: string;
  description: string | null;
  content: string | null;
  publishedAt: string;
  urlToImage: string | null;
  url: string;
}

export default async function handler(
  req: VercelRequest,
  res: VercelResponse
) {
  const apiKey = process.env.NEWS_API_KEY;

  if (!apiKey) {
    // Return mock data for demo purposes if API key is missing
    const mockNews = [
      {
        id: "live-mock-1",
        cat: "Live Intel",
        color: "primary",
        title: "Global Surge in AI-Driven Phishing Campaigns Detected",
        date: new Date().toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }),
        read: "5 min",
        summary: "Security researchers observe a 400% increase in highly personalized phishing emails generated by advanced LLMs, bypassing traditional spam filters.",
        tags: ["AI", "Phishing", "Threat Intel"],
        icon: "🤖",
        cover: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=70",
        url: "https://www.cyberhawk-ug.store/news"
      },
      {
        id: "live-mock-2",
        cat: "Data Breach",
        color: "danger",
        title: "Major Financial Institution Reports Potential Data Leak",
        date: new Date().toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }),
        read: "8 min",
        summary: "An unauthorized access to a legacy database may have exposed transaction records for millions of customers. Investigation is ongoing.",
        tags: ["Finance", "Breach", "Leak"],
        icon: "💸",
        cover: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=70",
        url: "https://www.cyberhawk-ug.store/news"
      }
    ];
    return res.status(200).json(mockNews);
  }

  try {
    // Fetch cybersecurity news from the last 2 days
    const query = "cybersecurity OR \"data breach\" OR ransomware OR malware";
    const url = `https://newsapi.org/v2/everything?q=${encodeURIComponent(query)}&sortBy=publishedAt&pageSize=12&apiKey=${apiKey}&language=en`;
    
    const response = await fetch(url);
    const data = await response.json();

    if (data.status !== "ok") {
      throw new Error(data.message || "Failed to fetch news");
    }

    // Map NewsAPI structure to our NewsItem structure
    const mappedNews = data.articles.map((article: NewsAPIArticle, index: number) => ({
      id: `live-${index}`,
      cat: "Live Intel",
      color: "primary",
      title: article.title,
      date: new Date(article.publishedAt).toLocaleDateString("en-US", { month: "short", day: "2-digit", year: "numeric" }),
      read: "3 min",
      summary: article.description || article.content?.substring(0, 150) + "...",
      tags: ["Breaking", "NewsAPI"],
      icon: "🌐",
      cover: article.urlToImage || "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?auto=format&fit=crop&w=800&q=70",
      url: article.url
    }));

    return res.status(200).json(mappedNews);
  } catch (error: unknown) {
    const err = error as Error;
    console.error("News API Error:", err.message);
    // Secure against information disclosure by returning a generic error
    return res.status(500).json({ error: "Failed to load live threat intelligence." });
  }
}
